export const ActionType = {
    SET_CRYPTO_DATA: "SET_CRYPTO_DATA",
    SET_NEWS: "SET_NEWS",
    SELECTED_CURRENCY: "SELECTED_CURRENCY",
    REMOVE_SELECTED_CURRENCY: "REMOVE_SELECTED_CURRENCY",
    SELECTED_CURRENCY_CHART: "SELECTED_CURRENCY_CHART",
    REMOVE_SELECTED_CURRENCY_CHART: "REMOVE_SELECTED_CURRENCY_CHART"

};